apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: elastichq
  name: elastichq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastichq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: elastichq
    spec:
      containers:
        - image: elastichq/elasticsearch-hq
          name: elastichq
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
