apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - args:
            - logstash
            - -f
            - /usr/share/logstash/config-dir/logstash.conf
          env:
            - name: POSTGRES_DB
              value: capstone_test
            - name: POSTGRES_HOST
              value: af763a614865c46fe92683f72ab426bb-113014642.us-west-2.elb.amazonaws.com:5432
            - name: POSTGRES_PASSWORD
              value: jOtNQq409iC8FAfUbts8dbp5OhusMUVnk72Nypy57oBUAsiYKsTlzdZ9B4jzvbc
            - name: POSTGRES_USER
              value: capstone_admin
          image: docker.elastic.co/logstash/logstash:7.0.0
          name: logstash
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config-dir
              name: logstash-claim0
            - mountPath: /usr/share/logstash/drivers
              name: logstash-claim1
      restartPolicy: Always
      volumes:
        - name: logstash-claim0
          persistentVolumeClaim:
            claimName: logstash-claim0
        - name: logstash-claim1
          persistentVolumeClaim:
            claimName: logstash-claim1
status: {}
