apiVersion: v1
kind: Service
metadata:
  name: petSearch
spec:
  type: LoadBalancer
  selector:
    app: petSearch
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
