openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
tags:
  - name: api
    description: Search for Pets

components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          type: string
        zip:
          type: string
        type:
          type: string
        breed:
          type: string
        age:
          type: string
        sex:
          type: string
    PetsList:
      $ref: '#/components/schemas/Pet'
      type: array

paths:
  /api/petSearch:
    get:
      tags:
        - api
      summary: Get all pets
      description: find all pets
      parameters:
        - name: zip
          in: query
          required: false
          schema:
            type: string
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: breed
          in: query
          required: false
          schema:
            type: string
        - name: age
          in: query
          required: false
          schema:
            type: string
        - name: sex
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: at least one pet exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetsList'
        '204':
          description: no pets found

